---
title: "605 Week 3 Discussion"
author: "Nathan Cooper"
date: "September 12, 2017"
#header-includes:
# - \usepackage{utf8}{inputenc} 
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### A Primer in Physics

#### The math

When I get to the actual problem below, you will hopefully recognize the mathematics very easily. What the math actually means in this case needs a little explanation. This is my attempt to do just that.

Quantum Mechanics (QM) is the physics used to describe molecules, atoms and sub-atomic particles. It was realized in the 19th Century that atoms exhibited behavior that was not readily explained by Classical Physics, the physics of the everyday human scaled world. Namely, these tiny objects behave in a discrete way, not a continuous way. 

The Eigenvalues and Eigenvectors (Eigenstates) that we are learning this week is an excellent way to model this behavior. Heisenberg (yes the Chemist in Breaking Bad took his street name from a Physicist, typical) worked out the Linear Algebra form of QM. Eigenstates are also a feature of Differential Equations (Diff-Eq), and Schroedinger worked out the Diff-Eq from resulting in Schroedinger's Equation:

$$
H|\Psi> = E|\Psi>
$$
Where H is the Hamiltonian and contains the information of the Energy of the system (the particle and it's surroundings). It can be a \textbf{matrix} or a Differential Equation. It turns out Heisenberg's and Schroedinger's systems are interchangeable.

$|\Psi>$ is the state \textbf{vector}. It contains the information about the state the particles are in. As example the $|n, l, m, s>$ numbers that are taught in High School Chemistry in the US. $\Psi$ is called the wave function in the Diff-Eq from and the $|>$ is not used. $<\Psi|\Psi>$ is the dot product of the state vector, and must equal 1, since it gives you the total probabilty of $\Psi$. (This a DATA 606 topic this week.)

E, the energy states of the system, are the eigenvalues of the system and they are paired with the eigenvectors of the system.

\textbf{What this equation is telling you is that if you do matrix multiplication, H by $|\Psi>$, on the left side of the equation what you get is the different states the system can be observed in, the eigenvectors of $H|\Psi>$ and the energies of those states E, the eigenvalues, of $H|\Psi>$.}

In Classical Physics H is called the Hamiltonian and it is the sum of kinetic and potential energy of a system. If you've taken Regent's Physics in New York, you've calculated this though they didn't call it by name. The difference is in Classical Mechanics you do algebra or calculus on H to find the positions and velocities of the system. In QM, H is an operator that does linear algebra or Diff-eq on $|\Psi>$ to find the measurables of the system.


#### The Neutrino

This problem deals with some unique behavior of a type of sub-atomic particle called Neutrinos. They have virtually no mass and absolutly no electric charge, and are generated during nuclear reactions when a proton is force to switch to neutron or vice-versa. This is called Beta-decay or inverse Beta-decay. Neutrinos travel so close to the speed of light that it's hard to measure the difference. In fact in 2011, the LHC claimed to have measures faster-than-light neutrinos which would have upended physics as we know it. It turns out there was a loose BNC cable in the computer that calulated the timing of the light beam.

Neutrinos are always paired with a partner particle when they are generated. If that partner is an electron or anti-electron, it's called an electron neutrino. In higher energy reactions, it can be paired with the electron's more massive cousin, the muon or anti-muon, in this case they are called muon neutrinos. There is a third type, tau, that extends the work below to a 3 x 3 matrix.

### Neutrino Oscillations 

> This is taken from D.J. Griffiths' Introduction to Quantum Mechanics, Prentice Hall, 1st Ed. 1995,  Problem 3.58.

The first part of this problem is finding the energy states of a system of electron neutrinos and muon neutrinos. This will be our focus, as it contains the math we are talking about this week.

Imagine a system in which there are just two linearly independent states:  

$$|1> =\begin{bmatrix}
1\\0 \end{bmatrix} \& |2> =\begin{bmatrix}
0\\1 \end{bmatrix}$$ 

Essentially, $|1>$ represents the electron neutrino and $|2>$ represents a muon neutrino.

The most general state is a linear combination:

$$|\Psi> = a|1> + b|2> \begin{bmatrix}
a\\b \end{bmatrix}$$


Where $a^{2} + b^{2} = 1$. Since, when you meaure the system you will see one type of neutrino or the other. For simplicty we can let $a = \pm 1/\sqrt{2}$ and $b = \pm 1/\sqrt{2}$. Such that:

$$|\Psi> =  \begin{bmatrix}
\pm 1/\sqrt{2}\\\pm 1/\sqrt{2} \end{bmatrix}$$

This means we'll have a 50-50 chance of measuring an electron neutrino or muon neutrino since:

$$<\Psi|\Psi> =\begin{bmatrix} \pm 1/\sqrt{2}, \pm 1/\sqrt{2} \end{bmatrix}\begin{bmatrix}
\pm 1/\sqrt{2}\\\pm 1/\sqrt{2} \end{bmatrix} = 1$$

Different state vectors $|Psi_{n}$> for the different $E_{n}$ energy eigenvalues will have different combinations of $\pm$'s.

Suppose the Hamiltonian matrix is:

$$H = \begin{bmatrix}
h&g\\
g&h
\end{bmatrix}
$$

Where h and g are real numbers with units of energy. Recall that Schroedinger's equation is:

$$H|\Psi> = E|\Psi>$$

That multiplying H times the state vector should yeild the Eigenvalues and Eigenvectors of the system. We need to solve the characteristic equation for H:

$$det(H - EI) = \begin{vmatrix} 
h - E & g \\ g & h-E
\end{vmatrix} = 0$$

Note that above, I is the idenyity matrix. Continuing: 

$$ (h - E)^2 - g^2 = 0$$


$$(h - E)^2 = g^2$$


There are two roots that give us the Eigenstates, $E_{1} = h+g$ and $E_{2} = h-g$.

As for what state vector $|\Psi_{1,2}>$ goes with what eigenstate$E_{1,2}$. In QM state vectors must be linearly independent such that $<\Psi_{1}|\Psi_{2}> = 0$. 

For simplicity, if we let $|\Psi_{1}> = \begin{bmatrix}  1/\sqrt{2} \\ 1/\sqrt{2} \end{bmatrix}$

And $|\Psi_{2}> = \begin{bmatrix}  1/\sqrt{2} \\ - 1/\sqrt{2} \end{bmatrix}$

Then:

$$
<\Psi_{1}|\Psi_{2}> =\begin{bmatrix}  1/\sqrt{2},  1/\sqrt{2} \end{bmatrix}\begin{bmatrix}
1/\sqrt{2}\\ - 1/\sqrt{2} \end{bmatrix} = 0
$$

So our soultions are:

$$E_{1}|\Psi_{1}> = (h+g) \begin{bmatrix}  1/\sqrt{2} \\ 1/\sqrt{2} \end{bmatrix}$$

and 

$$E_{2}|\Psi_{2}> = (h-g) \begin{bmatrix}  1/\sqrt{2} \\ -1/\sqrt{2} \end{bmatrix}$$

> The problem goes further to show that when you add time varience to this system it will flip back and forth between states so even if you know that you start with an electron neutrino you might measure it as muon neutrino some time later. Unfortunately that requires complex numbers and using exponential functions to model oscillations. This did solve a problem with "missing" nuetrinos from the sun:

https://en.wikipedia.org/wiki/Neutrino_oscillation

> And won a Nobel Prize in 2015. All with 2 x 2  and later 3 x 3 matrix linear algebra.